name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npm test

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --force
          npm run report
          name: Upload Allure Report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
         with:
          name: allure-report
          path: allure-report
    