name: Upload Artifact Test

on: [push]

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload a test file
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: README.md
